// Strategy and SWOT seed data

export const seedStrategies = [
  { competitorName: "Andritz", title: "Countering ANDRITZ", threatLevel: "High", threatDescription: "Global scale, 150+ year heritage, broad portfolio with thermal integration, and strong North American service footprint makes them a \"safe choice\" for complex projects.", winStrategy: "Acknowledge their global scale and references (builds trust), then pivot to agility, responsiveness, and lower total installed + lifecycle cost on North American biosolids projects." },
  { competitorName: "Alfa Laval", title: "Countering Alfa Laval", threatLevel: "High", threatDescription: "Very strong U.S. brand recognition with thousands of installations, complete municipal offering (decanters, SBRs, disc filters, heat exchangers), and extensive coast-to-coast commercial coverage.", winStrategy: "Probe for pain around slow decision cycles, lack of engineering access, and high OEM service costs. Offer side-by-side OPEX comparisons based on disposal, energy, and polymer." },
  { competitorName: "GEA Group", title: "Countering GEA", threatLevel: "Medium", threatDescription: "Strong brand in food/dairy/industrial processing, high-efficiency standardized decanters, and sustainability narrative with quantified impact. Less entrenched in U.S. municipal space.", winStrategy: "Leverage U.S. manufacturing advantage and faster lead times. Highlight local case studies and municipal-specific expertise over their European/international references." },
  { competitorName: "Flottweg", title: "Countering Flottweg", threatLevel: "Medium-High", threatDescription: "German-engineered high-performance centrifuge specialist with demonstrated sludge performance (16.5-20% DS). Strong wastewater positioning and 50+ years experience.", winStrategy: "Treat as technical peer on centrifuge performance and differentiate on U.S. manufacturing, service proximity, and application-specific customization in North America." },
  { competitorName: "HUBER", title: "Countering HUBER", threatLevel: "Low-Medium", threatDescription: "Strong in mechanical screening/presses with U.S. manufacturing in Denver, NC. Not a decanter competitor - focuses on screw/belt presses for municipal plants.", winStrategy: "Clarify that HUBER is mainly a press and mechanical treatment competitor, not a decanter specialist. Use dryness, polymer consumption, and automation (24/7 unattended) to justify centrifuge upgrades." },
  { competitorName: "CentriTek", title: "vs. CentriTek (Internal Threat)", threatLevel: "Medium", threatDescription: "Has deep knowledge of Centrisys but lacks resources and capabilities", winStrategy: "His primary weapon is price (no overhead), but emphasize his technical/liability risks. Win regulated bids by default (he cant). Build relationships with his past customers to understand what went wrong and position as upgrade." }
];

export const seedStrategyItems = [
  // Andritz
  { strategyTitle: "Countering ANDRITZ", type: "weakness_to_exploit", content: "Complex \"big company\" bureaucracy - Position as more agile and responsive for custom mid-size projects" },
  { strategyTitle: "Countering ANDRITZ", type: "weakness_to_exploit", content: "Premium pricing expectations - Contrast with lower-overhead, U.S.-made solutions delivering similar performance" },
  { strategyTitle: "Countering ANDRITZ", type: "weakness_to_exploit", content: "Diluted biosolids specialization - ANDRITZ messaging covers mining, pulp, etc. whereas Centrisys focuses exclusively on biosolids" },
  { strategyTitle: "Countering ANDRITZ", type: "weakness_to_exploit", content: "No rental fleet >21\": Position larger rental solutions for temporary/project needs" },
  { strategyTitle: "Countering ANDRITZ", type: "weakness_to_exploit", content: "Not centrifuge specialists: Emphasize deep centrifuge domain expertise vs. broader equipment portfolio" },
  { strategyTitle: "Countering ANDRITZ", type: "weakness_to_exploit", content: "Limited customization: Offer tailored configurations for specific applications" },
  { strategyTitle: "Countering ANDRITZ", type: "weakness_to_exploit", content: "Hydraulic drive service gaps: Market superior hydraulic system support capabilities" },
  { strategyTitle: "Countering ANDRITZ", type: "weakness_to_exploit", content: "No bowl sensors: Highlight advanced monitoring/automation features" },
  { strategyTitle: "Countering ANDRITZ", type: "winning_bid_strategy", content: "Highlight U.S. manufacturing and faster lead times for North American projects" },
  { strategyTitle: "Countering ANDRITZ", type: "winning_bid_strategy", content: "Emphasize direct engineering access and responsive decision-making vs. conglomerate hierarchy" },
  { strategyTitle: "Countering ANDRITZ", type: "winning_bid_strategy", content: "Provide detailed OPEX comparison including disposal, energy, and polymer costs" },
  { strategyTitle: "Countering ANDRITZ", type: "winning_bid_strategy", content: "Target applications requiring custom bowl/scroll designs they cant match" },
  { strategyTitle: "Countering ANDRITZ", type: "winning_bid_strategy", content: "Emphasize total cost of ownership including service/support efficiency" },
  { strategyTitle: "Countering ANDRITZ", type: "winning_bid_strategy", content: "Pursue rental opportunities above 21\" where they cannot compete" },
  { strategyTitle: "Countering ANDRITZ", type: "winning_bid_strategy", content: "Focus on food/industrial markets where they lack presence" },
  { strategyTitle: "Countering ANDRITZ", type: "winning_bid_strategy", content: "Highlight faster implementation & on-site repair capabilities" },
  { strategyTitle: "Countering ANDRITZ", type: "winning_bid_strategy", content: "Propose hybrid rental + purchase solutions" },
  // Alfa Laval
  { strategyTitle: "Countering Alfa Laval", type: "weakness_to_exploit", content: "Perceived as expensive and inflexible - Position as focused, cost-efficient alternative for mid-size utilities" },
  { strategyTitle: "Countering Alfa Laval", type: "weakness_to_exploit", content: "Centrifuge is one of many product lines - Contrast with our \"artisan-specialist\" deep centrifuge expertise" },
  { strategyTitle: "Countering Alfa Laval", type: "weakness_to_exploit", content: "Complex organization slows smaller projects - Offer direct access to U.S.-based specialist engineering team" },
  { strategyTitle: "Countering Alfa Laval", type: "weakness_to_exploit", content: "Poor mid-range bid performance: Dominate 15-24\" centrifuge market where theyre weakest" },
  { strategyTitle: "Countering Alfa Laval", type: "weakness_to_exploit", content: "Bad technical support: Emphasize responsive support & local expertise" },
  { strategyTitle: "Countering Alfa Laval", type: "weakness_to_exploit", content: "Tariff impacts: If competing on imports, highlight domestic manufacturing advantages" },
  { strategyTitle: "Countering Alfa Laval", type: "weakness_to_exploit", content: "Mechanical sealing issues: Promote superior sealing system reliability" },
  { strategyTitle: "Countering Alfa Laval", type: "weakness_to_exploit", content: "Bearing grease limitation: Highlight machines that run grease past 29\" without performance loss" },
  { strategyTitle: "Countering Alfa Laval", type: "winning_bid_strategy", content: "Target pain around slow response times and high OEM service costs" },
  { strategyTitle: "Countering Alfa Laval", type: "winning_bid_strategy", content: "Present side-by-side lifecycle cost analysis emphasizing service and parts accessibility" },
  { strategyTitle: "Countering Alfa Laval", type: "winning_bid_strategy", content: "Leverage digital content and technical authority to demonstrate specialized expertise" },
  { strategyTitle: "Countering Alfa Laval", type: "winning_bid_strategy", content: "Aggressively price mid-range (15-24\") bids where they falter" },
  { strategyTitle: "Countering Alfa Laval", type: "winning_bid_strategy", content: "Build case studies around faster, more responsive support" },
  { strategyTitle: "Countering Alfa Laval", type: "winning_bid_strategy", content: "Address retrofitting Sharples machines directly (their gap)" },
  { strategyTitle: "Countering Alfa Laval", type: "winning_bid_strategy", content: "Emphasize spare parts availability & quick delivery vs. their high costs" },
  { strategyTitle: "Countering Alfa Laval", type: "winning_bid_strategy", content: "Highlight superior bearing life and machine reliability metrics" },
  { strategyTitle: "Countering Alfa Laval", type: "winning_bid_strategy", content: "Target customers frustrated with their technical support reputation" },
  // GEA Group
  { strategyTitle: "Countering GEA", type: "weakness_to_exploit", content: "Less recognized in U.S. municipal wastewater vs. food/industrial - Highlight our municipal-specific track record" },
  { strategyTitle: "Countering GEA", type: "weakness_to_exploit", content: "European lead times and manufacturing - Contrast with domestic supply chain and faster delivery" },
  { strategyTitle: "Countering GEA", type: "weakness_to_exploit", content: "Case studies focus on Europe/international - Present local North American success stories" },
  { strategyTitle: "Countering GEA", type: "weakness_to_exploit", content: "Poor service reputation: Repairs must go back to Germany = major customer pain point" },
  { strategyTitle: "Countering GEA", type: "weakness_to_exploit", content: "Long lead times: Everything comes from Germany - highlight speed advantage" },
  { strategyTitle: "Countering GEA", type: "weakness_to_exploit", content: "No local support: Pricing/quoting from Germany creates friction & slow sales cycle" },
  { strategyTitle: "Countering GEA", type: "weakness_to_exploit", content: "Mining reputation: Not trusted in certain industries - expand presence" },
  { strategyTitle: "Countering GEA", type: "weakness_to_exploit", content: "Expensive spare parts: Stress affordable parts availability" },
  { strategyTitle: "Countering GEA", type: "weakness_to_exploit", content: "Limited customization: Inflexible on T&Cs and specifications" },
  { strategyTitle: "Countering GEA", type: "winning_bid_strategy", content: "Emphasize \"Made in USA\" for Buy American preferences common in public procurement" },
  { strategyTitle: "Countering GEA", type: "winning_bid_strategy", content: "Demonstrate understanding of specific North American regulatory and PFAS challenges" },
  { strategyTitle: "Countering GEA", type: "winning_bid_strategy", content: "Offer faster customization and responsive local support vs. standardized European equipment" },
  { strategyTitle: "Countering GEA", type: "winning_bid_strategy", content: "Compete on total cost: emphasize lower service costs vs. their long downtime/repair times" },
  { strategyTitle: "Countering GEA", type: "winning_bid_strategy", content: "Position speed: \"Centrifuge fixed locally in 48 hours, not 3 months in Germany\"" },
  { strategyTitle: "Countering GEA", type: "winning_bid_strategy", content: "Target non-dairy applications where theyre weaker (mining remediation, industrial)" },
  { strategyTitle: "Countering GEA", type: "winning_bid_strategy", content: "Offer flexible T&Cs and specification accommodations they refuse" },
  { strategyTitle: "Countering GEA", type: "winning_bid_strategy", content: "Build energy efficiency story to compete with their EngySpeed advantage" },
  { strategyTitle: "Countering GEA", type: "winning_bid_strategy", content: "Target customers who tried GEA and had service nightmares" },
  { strategyTitle: "Countering GEA", type: "winning_bid_strategy", content: "Use AI/digital monitoring in own offering to neutralize their tech advantage" },
  // Flottweg
  { strategyTitle: "Countering Flottweg", type: "weakness_to_exploit", content: "Narrower portfolio - They lack the thermal/biological integration options but this is rarely a disadvantage head-to-head" },
  { strategyTitle: "Countering Flottweg", type: "weakness_to_exploit", content: "German manufacturing with longer lead times - Position domestic manufacturing as faster and lower risk" },
  { strategyTitle: "Countering Flottweg", type: "weakness_to_exploit", content: "Less brand recognition at small U.S. municipals - Leverage established relationships where they need to \"explain who they are\"" },
  { strategyTitle: "Countering Flottweg", type: "weakness_to_exploit", content: "Only one service location (KY): Geography = major disadvantage for West/East Coast" },
  { strategyTitle: "Countering Flottweg", type: "weakness_to_exploit", content: "Expensive spares logistics: Everything from Germany = shipping costs & delays" },
  { strategyTitle: "Countering Flottweg", type: "weakness_to_exploit", content: "Long lead times: German manufacturing = not ideal for quick delivery needs" },
  { strategyTitle: "Countering Flottweg", type: "weakness_to_exploit", content: "Weak rep network: Limited sales coverage vs. established US competitors" },
  { strategyTitle: "Countering Flottweg", type: "weakness_to_exploit", content: "Not strong municipally: Gap in municipal wastewater treatment segment" },
  { strategyTitle: "Countering Flottweg", type: "weakness_to_exploit", content: "Lower oil process performance: Highlight superior performance in food oils/rendering" },
  { strategyTitle: "Countering Flottweg", type: "winning_bid_strategy", content: "Treat as technical peer - acknowledge German engineering quality while differentiating on U.S. presence" },
  { strategyTitle: "Countering Flottweg", type: "winning_bid_strategy", content: "Emphasize faster parts delivery and service response from domestic manufacturing base" },
  { strategyTitle: "Countering Flottweg", type: "winning_bid_strategy", content: "Highlight application-specific customization for North American biosolids market conditions" },
  { strategyTitle: "Countering Flottweg", type: "winning_bid_strategy", content: "Leverage geographic advantage: \"Local service, not 2000 miles away\"" },
  { strategyTitle: "Countering Flottweg", type: "winning_bid_strategy", content: "Target West Coast/Northeast bids where they have slow response" },
  { strategyTitle: "Countering Flottweg", type: "winning_bid_strategy", content: "Build case studies in municipal wastewater where theyre weak" },
  { strategyTitle: "Countering Flottweg", type: "winning_bid_strategy", content: "Offer supply chain advantages: faster delivery, lower spare parts costs" },
  { strategyTitle: "Countering Flottweg", type: "winning_bid_strategy", content: "Compete directly on food/beverage with better oil process performance claims" },
  { strategyTitle: "Countering Flottweg", type: "winning_bid_strategy", content: "Emphasize US-centric inventory vs. their Germany-dependent supply chain" },
  { strategyTitle: "Countering Flottweg", type: "winning_bid_strategy", content: "Target customers frustrated with Flottweg lead times" },
  { strategyTitle: "Countering Flottweg", type: "winning_bid_strategy", content: "Build stronger rep network in regions where theyre absent" },
  // HUBER
  { strategyTitle: "Countering HUBER", type: "weakness_to_exploit", content: "Not a decanter competitor - Focus on different technology category (presses vs. centrifuges)" },
  { strategyTitle: "Countering HUBER", type: "weakness_to_exploit", content: "Lower dryness from belt/screw presses - Present lifecycle economics where disposal/hauling dominates cost" },
  { strategyTitle: "Countering HUBER", type: "weakness_to_exploit", content: "Higher polymer consumption with presses - Demonstrate polymer savings with centrifuge technology" },
  { strategyTitle: "Countering HUBER", type: "winning_bid_strategy", content: "Educate on decanter vs. press economics - show total cost of ownership including disposal costs" },
  { strategyTitle: "Countering HUBER", type: "winning_bid_strategy", content: "Emphasize 24/7 unattended operation and automation capabilities of centrifuges" },
  { strategyTitle: "Countering HUBER", type: "winning_bid_strategy", content: "Target plants where rising disposal costs and PFAS constraints justify centrifuge investment over presses" },
  // CentriTek
  { strategyTitle: "vs. CentriTek (Internal Threat)", type: "weakness_to_exploit", content: "No ISO certification: Disqualifies from regulated/pharma bidding" },
  { strategyTitle: "vs. CentriTek (Internal Threat)", type: "weakness_to_exploit", content: "No bonding capability: Cant handle large project contracts" },
  { strategyTitle: "vs. CentriTek (Internal Threat)", type: "weakness_to_exploit", content: "Limited capital/equipment: No cranes, no warranty - major liability" },
  { strategyTitle: "vs. CentriTek (Internal Threat)", type: "weakness_to_exploit", content: "Knowledge gaps: Doesnt understand OEM specs or clearances" },
  { strategyTitle: "vs. CentriTek (Internal Threat)", type: "weakness_to_exploit", content: "No shop infrastructure: Cannot provide proper service/repairs" },
  { strategyTitle: "vs. CentriTek (Internal Threat)", type: "winning_bid_strategy", content: "Directly target regulated industries (pharma, food, municipal) where ISO is required" },
  { strategyTitle: "vs. CentriTek (Internal Threat)", type: "winning_bid_strategy", content: "Emphasize warranty and liability protection vs. his no-warranty model" },
  { strategyTitle: "vs. CentriTek (Internal Threat)", type: "winning_bid_strategy", content: "Highlight shop capabilities and equipment (cranes, facilities, tools)" },
  { strategyTitle: "vs. CentriTek (Internal Threat)", type: "winning_bid_strategy", content: "Target large project bids where bonding is required" },
  { strategyTitle: "vs. CentriTek (Internal Threat)", type: "winning_bid_strategy", content: "Monitor and counter his bids by educating prospects on risk/liability" }
];
